my_string = input('Введите ваш фрукт: ')
print(my_string)
my_string = input('Введите ваш фрукт: ')
print(my_string.upper())
my_string = input('Введите ваш фрукт: ')
print(my_string.lower())
my_string = input('Введите ваш фрукт и овощ: ')
print(my_string.replace(' ',''))
my_string = input('Введите ваш фрукт: ')
print(my_string[0])
my_string = input('Введите ваш фрукт: ')
print(my_string[-1])